name: CI

on: [push, pull_request]
jobs:
  test_glibc_llvm:
    name: "Test with clang/glibc/libc++/lld on Arch Linux"
    runs-on: ubuntu-latest
    container:
        image: archlinux:latest
    steps:
    - run: sed -i 's/SigLevel    = Required DatabaseOptional/SigLevel    = Optional TrustAll/' /etc/pacman.conf
    - run: pacman --noconfirm --noprogressbar -Syyu
    - run: pacman --noconfirm --noprogressbar -Sy git clang lld libc++ pkgconf meson ninja wayland wayland-protocols libinput libxkbcommon pixman glm libdrm libglvnd cairo pango systemd scdoc base-devel seatd jsoncpp pcre2

    - name: Wayfire
      uses: actions/checkout@v2
      with:
        repository: WayfireWM/wayfire
        path: wayfire
    - run: cd wayfire && git submodule sync --recursive && git submodule update --init --force --recursive && meson build --prefix=/usr && ninja -v -Cbuild && ninja -v -Cbuild install && cd ..
    - name: Wayfire IPC
      uses: actions/checkout@v2
      with:
        path: wayfire-ipc
    - run: cd wayfire-ipc && meson build && ninja -v -Cbuild
  test_glibc_llvm_xwayland:
    name: "Test with clang/glibc/libc++/lld on Arch Linux with Xwayland"
    runs-on: ubuntu-latest
    container:
        image: archlinux:latest
    steps:
    - run: sed -i 's/SigLevel    = Required DatabaseOptional/SigLevel    = Optional TrustAll/' /etc/pacman.conf
    - run: pacman --noconfirm --noprogressbar -Syyu
    - run: pacman --noconfirm --noprogressbar -Sy git clang lld libc++ pkgconf meson ninja wayland wayland-protocols libinput libxkbcommon pixman glm libdrm libglvnd cairo pango systemd scdoc base-devel seatd jsoncpp pcre2 xorg-xwayland xcb-util xcb-util-cursor xcb-util-errors xcb-util-image xcb-util-keysyms xcb-util-renderutil xcb-util-wm 

    - name: Wayfire
      uses: actions/checkout@v2
      with:
        repository: WayfireWM/wayfire
        path: wayfire
    - run: cd wayfire && git submodule sync --recursive && git submodule update --init --force --recursive && meson build --prefix=/usr && ninja -v -Cbuild && ninja -v -Cbuild install && cd ..
    - name: Wayfire IPC
      uses: actions/checkout@v2
      with:
        path: wayfire-ipc
    - run: cd wayfire-ipc && meson build && ninja -v -Cbuild
  test_code_style:
    name: "Check code style with uncrustify"
    runs-on: ubuntu-latest
    steps:
    - run: sudo apt-get update
    - run: sudo apt-get install -y git cmake gcc make
    - name: Build Uncrustify
      uses: actions/checkout@v2
      with:
        repository: ammen99/uncrustify
        path: uncrustify
    - run: cd uncrustify && mkdir build && cd build && cmake .. && make && cd ../..
    - name: Run Uncrustify Check
      uses: actions/checkout@v2
      with:
        path: wayfire-ipc
    - run: cd wayfire-ipc && wget https://raw.githubusercontent.com/WayfireWM/wayfire/master/uncrustify.ini
    - run: cd wayfire-ipc && git ls-files | grep "hpp$\|cpp$" | xargs ../uncrustify/build/uncrustify -c uncrustify.ini --no-backup --replace
    - run: cd wayfire-ipc && git diff --exit-code
